const parts = {
"parts.adjective.verb": "형동사",
"parts.adjective": "형용사",
"parts.adv2": "부사, 부사",
"parts.adv": "부사",
"parts.adverb": "부사",
"parts.adverbinterjection": "부사·감탄사",
"parts.affix": "접사",
"parts.an.interjection": "간투사",
"parts.assistantadjective": "보조형용사",
"parts.assistantverb": "보조동사",
"parts.auxiliary": "조동사",
"parts.boundnoun": "의존명사",
"parts.conjunction": "접속사",
"parts.determiner": "관형사",
"parts.determinerinterjection": "관형사·감탄사",
"parts.determinernoun": "관형사·명사",
"parts.ending": "어미",
"parts.feminine": "여성명사",
"parts.interjection": "감탄사",
"parts.interjectionnoun": "감탄사·명사",
"parts.interrogative": "의문사",
"parts.intransitive.verb": "자동사",
"parts.masculine": "남성명사",
"parts.n.collective": "집합명사",
"parts.n.num": "명수사",
"parts.n": "명사",
"parts.nounadverb": "명사·부사",
"parts.num": "수사",
"parts.numeraldeterminer": "수사·관형사",
"parts.numeraldeterminernoun": "수사·관형사·명사",
"parts.parts.neuter": "중성명사",
"parts.perceptive.verb": "지각동사",
"parts.possessive.pron": "소유 대명사",
"parts.postposition": "조사",
"parts.prefix": "접두사",
"parts.preposition": "전치사",
"parts.pron": "대명사",
"parts.pronounadverb": "대명사·부사",
"parts.pronoundeterminer": "대명사·관형사",
"parts.pronouninterjection": "대명사·감탄사",
"parts.relative": "관계사",
"parts.relynouninvestigation": "의존명사·조사",
"parts.suffix": "접미사",
"parts.transitive.verb": "타동사",
"parts.verb": "동사",
"parts.verbadjective": "동사·형용사",
"conjugation.1st.person.plural": "1인칭 복수",
"conjugation.1st.person.singular": "1인칭 단수",
"conjugation.1st.person": "1인칭",
"conjugation.2nd.person.plural": "2인칭 복수",
"conjugation.2nd.person.singular": "2인칭 단수",
"conjugation.2nd.person": "2인칭",
"conjugation.3rd.person.plural": "3인칭 복수",
"conjugation.3rd.person.singular": "3인칭 단수",
"conjugation.3rd.person": "3인칭",
"conjugation.accusative": "대격",
"conjugation.dative": "여격",
"conjugation.feminine.plural": "여성 복수",
"conjugation.feminine.singular": "여성 단수",
"conjugation.feminine": "여성",
"conjugation.future.adverbial": "미래부사",
"conjugation.future.participle.active": "미래분사능동",
"conjugation.future.participle.passive": "미래분사수동",
"conjugation.future.participle": "미래분사",
"conjugation.future.perfect.progressive": "미래완료진행형",
"conjugation.future.progressive": "미래진행형",
"conjugation.future.tense": "미래시제",
"conjugation.genitive": "소유격",
"conjugation.instrumental": "조격",
"conjugation.masculine.plural": "남성 복수",
"conjugation.masculine.singular": "남성 단수",
"conjugation.masculine": "남성",
"conjugation.neuter.plural": "중성 복수",
"conjugation.neuter.singular": "중성 단수",
"conjugation.neuter": "중성",
"conjugation.nominative": "주격",
"conjugation.past.adverbial": "과거부사",
"conjugation.past.participle.active": "과거분사능동",
"conjugation.past.participle.passive": "과거분사수동",
"conjugation.past.participle": "과거분사",
"conjugation.past.perfect.progressive": "과거완료진행형",
"conjugation.past.progressive": "과거진행형",
"conjugation.past.tense": "과거시제",
"conjugation.plural": "복수",
"conjugation.prepositional": "전치격",
"conjugation.present.adverbial": "현재부사",
"conjugation.present.participle.active": "현재분사능동",
"conjugation.present.participle.passive": "현재분사수동",
"conjugation.present.participle": "현재분사",
"conjugation.present.perfect.progressive": "현재완료진행형",
"conjugation.present.progressive": "현재진행형",
"conjugation.present.tense": "현재시제",
"conjugation.singular": "단수",
"alldic.busa.daimingsa": "부사, 대명사",
"alldic.busa.guanxi": "부사, 관계사",
"alldic.busa.yiwen": "부사, 의문사",
"alldic.busa.zhenqi": "부사, 전치사",
"alldic.busa.zhesaosa": "부사, 접속사",
"alldic.busu.xingrongci": "부사, 형용사",
"alldic.buzheng.nm": "부정대명사" }

module.exports = {parts};